name: learn-github-actions
on: [ push ]
jobs:
  check-bats-version:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: echo "$ID_RSA_PUB"
        env:
          id_rsa_pub: ${{ secrets.ID_RSA_PUB }}
      - run: npm install
      - run: npm run dev-build