name: learn-github-actions
on: [ push ]
jobs:
  check-bats-version:
    runs-on: ubuntu-20.04
    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-node@v1
#      - run: npm install
#      - run: npm run dev-build
      - run: mkdir ~/public
      - run: echo "qwer-ty" > ~/public/qwer.txt
      - name: Publish
        uses: nogsantos/scp-deploy@master
        with:
          src: ./dist/*
          host: ${{ secrets.SSH_HOST }}
          remote: ${{ secrets.SSH_DIR }}
          key: ${{ secrets.SSH_RSA }}
          user: ${{ secrets.SSH_USER }}

