name: learn-github-actions
on: [ push ]
jobs:
  check-bats-version:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install
      - run: npm run dev-build
      - run: echo ${{secrets.ID_RSA_PUB}} >> ~/.ssh/rsa_pub
      - run: scp -r ./public root@37.228.117.174:~/public

